- block:
  - name: prepare image information (set name and section where missing)
    vars: # keep .name if it exists, otherwise take the last part of the source image
      image_new: "{{ image | combine({
        'name':    image.name    | default( (image.source | default('')).split('/')|last),
        'tag': image.tag  | default( software[image.name].version ),
        'requires': image.requires | default( ['scratch'] ),
        'section': image.section | default( default_section|default('') )
        }) }}"
    set_fact:
      images_new: "{{ images_new | default([]) + [image_new] }}"
    loop: "{{ images }}"
    loop_control:
      loop_var: "image"    

  - set_fact:
      images: "{{ images_new + [{'name': 'scratch', 'section': 'build', 'tag': builder.portage, 'build': { 'configure_builder': builder.configure_builder, 'purge_image_root': builder.purge_image_root }, 'type': 'gentoo-image-builder'}] }}"
      images_processed: "{{ [] }}"
      image_build_sources: "{{ role_path }}/templates/image-build/"

  - debug:
      msg: "updated list of images\n{{ images | to_nice_yaml }}\nlimit_images:\n{{ limit_images | to_nice_yaml }}\n"

  - name: handle images
    include_tasks: image.yaml
    vars:
      image: "image0"
    when: (limit_images is not defined or image0.name is in limit_images) and image0.name not in images_processed
    loop: "{{ images }}"
    loop_control:
      loop_var: "image0"
  run_once: true
